function cameraKey(){return `${styleId}/${editComponent||sel}/${editComponent?editScope:''}`;}
function updateCamera(svg,bounds){const key=cameraKey();if(!camera||camera.key!==key)camera={key,base:bounds.slice(),box:bounds.slice(),manual:false};else if(!camera.manual&&!drag){camera.base=bounds.slice();camera.box=bounds.slice();}svg.setAttribute('viewBox',camera.box.join(' '));$('zoomLevel').textContent=Math.round(camera.base[2]/camera.box[2]*100)+'%';svg.style.cursor=tool==='pan'||spaceDown?'grab':'';}
function zoomEditor(factor,clientPoint){if(!camera)return;const svg=$('editorSvg'),old=camera.box.slice(),percent=camera.base[2]/old[2],target=Math.max(.25,Math.min(32,percent*factor)),ratio=percent/target;let anchor=[old[0]+old[2]/2,old[1]+old[3]/2];if(clientPoint){const p=svg.createSVGPoint();p.x=clientPoint[0];p.y=clientPoint[1];const q=p.matrixTransform(svg.getScreenCTM().inverse());anchor=[q.x,q.y];}camera.box=[anchor[0]+(old[0]-anchor[0])*ratio,anchor[1]+(old[1]-anchor[1])*ratio,old[2]*ratio,old[3]*ratio];camera.manual=true;renderEditor();}
function moveEndpoint(path,index,handle,dx,dy){const c=path[index];if(handle){c['x'+handle]+=dx;c['y'+handle]+=dy;return;}const lastIndex=path.at(-1)?.type==='Z'?path.length-2:-1,linked=lastIndex>0&&path[0].x===path[lastIndex].x&&path[0].y===path[lastIndex].y;const ids=linked&&(index===0||index===lastIndex)?[0,lastIndex]:[index];for(const i of ids){const q=path[i];q.x+=dx;q.y+=dy;if(q.type==='C'){q.x2+=dx;q.y2+=dy;}const next=path[i+1];if(next?.type==='C'){next.x1+=dx;next.y1+=dy;}}}
function finishPan(){if(!panDrag)return;panDrag=null;renderEditor();}
$('editorSvg').addEventListener('wheel',e=>{e.preventDefault();zoomEditor(Math.exp(-Math.max(-120,Math.min(120,e.deltaY))*.003),[e.clientX,e.clientY]);},{passive:false});
$('editorSvg').addEventListener('pointerdown',e=>{if(tool!=='pan'&&!spaceDown&&e.button!==1)return;e.preventDefault();e.stopImmediatePropagation();const svg=$('editorSvg'),pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const q=pt.matrixTransform(svg.getScreenCTM().inverse());panDrag={start:[q.x,q.y],box:camera.box.slice(),matrix:svg.getScreenCTM().inverse()};camera.manual=true;svg.setPointerCapture(e.pointerId);svg.style.cursor='grabbing';},true);
$('editorSvg').addEventListener('pointermove',e=>{if(!panDrag)return;e.preventDefault();e.stopImmediatePropagation();const pt=$('editorSvg').createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const q=pt.matrixTransform(panDrag.matrix);camera.box=[panDrag.box[0]-(q.x-panDrag.start[0]),panDrag.box[1]-(q.y-panDrag.start[1]),panDrag.box[2],panDrag.box[3]];$('editorSvg').setAttribute('viewBox',camera.box.join(' '));},true);
$('editorSvg').addEventListener('pointerup',finishPan);$('editorSvg').addEventListener('pointercancel',finishPan);
document.addEventListener('keydown',e=>{if(!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)&&e.code==='Space'){e.preventDefault();spaceDown=true;$('editorSvg').style.cursor='grab';}});
document.addEventListener('keyup',e=>{if(e.code==='Space'){spaceDown=false;finishPan();$('editorSvg').style.cursor=tool==='pan'?'grab':'';}});
window.addEventListener('blur',()=>{spaceDown=false;finishPan();});
