const RELATION_LABELS={independent:'independente',detached:'desvinculado',components:'ligado a componentes',masters:'ligado aos mestres','linked to components with overrides':'ligado a componentes com exceções','linked to masters with overrides':'ligado aos mestres com exceções','locally corrected':'corrigido localmente'};
function styleLabel(name){return name.replace(/^(Light|Medium|Semibold|Bold)(?= |$)/,w=>({Light:'Leve',Medium:'Médio',Semibold:'Seminegrito',Bold:'Negrito'})[w]).replace(/ Italic$/,' Itálico').replace(/ Oblique$/,' Oblíquo');}
const COMPONENT_LABELS={vertical:'Haste vertical',horizontal:'Travessa horizontal',diagonal:'Haste para diagonais',bowl:'Bojo e contraforma',arch:'Arco e ombro',serif:'Serifa',terminal:'Terminal e ponto',acute:'Acento agudo',grave:'Acento grave',circumflex:'Circunflexo',tilde:'Til',diaeresis:'Trema',cedilla:'Cedilha'};
const FEATURE_LABELS={cap:'Altura das maiúsculas',xheight:'Altura-x',ascender:'Altura das ascendentes',descender:'Profundidade das descendentes',stem:'Espessura vertical',hstem:'Espessura horizontal',width:'Largura',contrast:'Contraste de traço',axis:'Eixo de contraste',overshoot:'Compensação das curvas',aperture:'Abertura',slant:'Inclinação adicional'};
function referenceConstructionProposals(){
 const references=P.references.filter(r=>r.confirmed&&r.primary&&r.style===styleId);const changes=[],missing=[],known=new Set();
 const add=(key,contours,r,method,confidence,selected=true)=>{if(known.has(key)||!contours.length)return;validateContours(contours);const b=bbox(contours);if(!b.w||!b.h)return;known.add(key);changes.push({key,contours:clone(contours),reference:r.id,char:r.char,source:`${r.char} / ${r.name}`,method,confidence,selected,approved:false});};
 // Prefer complete established bowls over uncertain fragments from a single letter.
 for(const r of references){const g=style().glyphs[r.char],q=r.reconstruction||g?.contours;if(!q?.length)continue;
  if('Oo0'.includes(r.char)&&q.length>=2)add('bowl',q,r,'Contornos completos, incluindo contraforma','Extraído diretamente');
  if(r.char==='n')add('arch',q,r,'Arco completo da letra n','Extraído diretamente');
 }
 for(const r of references){const q=r.reconstruction||style().glyphs[r.char]?.contours;if(!q?.length)continue;const bounds=bbox(q),stem=r.analysis?.stem||P.features.stem.effective;
  let vertical=null,horizontal=null,diagonal=null;
  for(const p of q)for(let i=1;i<p.length;i++){const a=p[i-1],b=p[i];if(b.type!=='L'||a.x===undefined)continue;const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);if(Math.abs(dx)<1&&Math.abs(dy)>bounds.h*.55&&(!vertical||Math.abs(dy)>vertical.length))vertical={x:a.x,y:Math.min(a.y,b.y),length:Math.abs(dy)};if(Math.abs(dy)<1&&Math.abs(dx)>bounds.w*.45&&(!horizontal||Math.abs(dx)>horizontal.length))horizontal={x:Math.min(a.x,b.x),y:a.y,length:Math.abs(dx)};if(Math.abs(dx)>len*.18&&Math.abs(dy)>len*.35&&len>bounds.h*.6&&(!diagonal||len>diagonal.length))diagonal={a:[a.x,a.y],b:[b.x,b.y],length:len};}
  if(vertical){const v=vertical,width=Math.min(stem,bounds.w*.35),rings=flatten(q),positive=rings.filter(ring=>inside([v.x+Math.min(width*.35,12),v.y+v.length*.19],ring)).length%2,region=[positive?v.x:v.x-width,v.y,width,v.length];add('vertical',boolean(q,[rect(...region)],'intersection'),r,'Recorte em torno da borda vertical longa; revise junções e cortes','Recorte mensurável; requer revisão');}
  if(horizontal){const h=horizontal,t=P.features.hstem.effective,rings=flatten(q),positive=rings.filter(ring=>inside([h.x+h.length*.5,h.y+Math.min(t*.35,12)],ring)).length%2,region=[h.x,positive?h.y:h.y-t,h.length,t];add('horizontal',boolean(q,[rect(...region)],'intersection'),r,'Recorte em torno da borda horizontal longa; revise junções','Recorte mensurável; requer revisão');}
  if(diagonal){const d=diagonal,u=unitVector([d.b[0]-d.a[0],d.b[1]-d.a[1]]),n=[-u[1],u[0]],from=d.a.map((v,k)=>v+u[k]*d.length*.62),to=d.a.map((v,k)=>v+u[k]*d.length*.9),wide=stem*1.5,points=[from.map((v,k)=>v+n[k]*wide),to.map((v,k)=>v+n[k]*wide),to.map((v,k)=>v-n[k]*wide),from.map((v,k)=>v-n[k]*wide)],clip=[M(...points[0]),...points.slice(1).map(p=>L(...p)),Z()],part=boolean(q,[clip],'intersection'),upright=mapContours(part,(x,y)=>[(x-from[0])*n[0]+(y-from[1])*n[1],(x-from[0])*u[0]+(y-from[1])*u[1]]);add('diagonal',upright,r,'Trecho da diagonal real, convertido para eixo local; revise cortes','Extração com transformação explícita');}
  if(!known.has('arch')&&'hm'.includes(r.char)){const height=P.features.xheight.effective;add('arch',boolean(q,[rect(bounds.x,0,bounds.w,height)],'intersection'),r,'Recorte da região da altura-x; pode conter mais de um ombro','Alternativa a revisar',false);}
  if(!known.has('bowl')&&'abdpqgBPRD'.includes(r.char)&&q.length>1){const rings=flatten(q),counter= q.find((p,i)=>i>0&&rings[i]&&inside(rings[i][0],rings[0]));if(counter){const b=bbox([counter]),t=stem,region=[b.x-t,b.y-t,b.w+2*t,b.h+2*t];add('bowl',boolean(q,[rect(...region)],'intersection'),r,'Região ao redor da contraforma; junções e assimetrias permanecem para revisão','Alternativa parcial; não é um O deduzido',false);}}
 }
 if(!known.has('diagonal')&&known.has('vertical')){const v=changes.find(c=>c.key==='vertical');changes.push({...clone(v),key:'diagonal',method:'Reutilizar a haste como base das diagonais; o ângulo e as junções são decisões novas',confidence:'Adaptação proposta, não observada',selected:false});known.add('diagonal');}
 for(const key of ['vertical','horizontal','diagonal','bowl','arch'])if(!known.has(key))missing.push(`${COMPONENT_LABELS[key]}: as referências não estabelecem esta peça. Desenhe, importe outro exemplo ou aceite uma proposta original explicitamente.`);
 return {changes,missing,references};
}
function proposeReferenceConstruction(){
 const result=referenceConstructionProposals();if(!result.references.length)throw Error('Confirme uma referência e escolha seu estilo antes de extrair construções.');
 const body=$('modalBody');body.replaceChildren();$('modalTitle').textContent='Construções a partir das suas referências';
 const intro=document.createElement('p');intro.className='hint';intro.textContent='Peças extraídas permanecem sem aprovação. Selecione as que deseja usar; revise os recortes antes de aprovar. Glifos existentes não são substituídos.';body.append(intro);
 const pair=document.createElement('div');pair.className='previewpair';body.append(pair);
 const preview=item=>{pair.replaceChildren();for(const [label,contours] of [['Peça atual',component(item.key).contours],['Proposta da referência',item.contours]]){const wrap=document.createElement('div'),title=document.createElement('p');title.textContent=label;const svg=node('svg');const b=bbox(contours);svg.setAttribute('viewBox',`${b.x-30} ${-b.y-b.h-30} ${b.w+60} ${b.h+60}`);node('path',{d:pathD(contours),transform:'scale(1 -1)',fill:'var(--ink)','fill-rule':'nonzero'},svg);wrap.append(title,svg);pair.append(wrap);}};
 const list=document.createElement('div');list.className='checklist';for(const item of result.changes){const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=item.selected;check.onchange=()=>item.selected=check.checked;const text=document.createElement('span');text.textContent=`${COMPONENT_LABELS[item.key]} · ${item.source} · ${item.confidence}. ${item.method}`;text.onclick=()=>preview(item);label.append(text,check);list.append(label);}body.append(list);
 if(result.changes.length)preview(result.changes[0]);for(const text of result.missing){const p=document.createElement('p');p.className='notice';p.textContent=text;body.append(p);}
 componentPending=result.changes;$('modalApply').hidden=!result.changes.length;$('modal').hidden=false;
}
function constructionOverview(){const rows=Object.keys(COMPONENT_LABELS).map(key=>{const c=component(key),derived=!!c.derivation||!['Independent starter drawing','Desenho original de exemplo'].includes(c.source);return `${COMPONENT_LABELS[key]}: ${c.approved?'aprovado':'a revisar'} · ${derived?c.source:'proposta original; não extraída da sua referência'}`;});$('referenceCoverage').textContent=rows.slice(0,7).join('\n');}
function diagnosticPortuguese(value,key=''){
 const labels={revision:'revisão',style:'estilo',relationship:'vínculo',needsReview:'precisa de revisão',source:'origem',components:'componentes',componentVersions:'versões das peças',measurements:'medidas',styleStem:'espessura do estilo',constructionConstraints:'restrições de construção',decisions:'decisões',shared:'compartilhado',glyph:'glifo',designNotes:'notas de desenho',anchors:'âncoras',adjustments:'correções ópticas',requestedAnchor:'âncora solicitada',requestedPoint:'ponto solicitado',requestedMetrics:'métricas solicitadas',metricConstraint:'restrição métrica',limits:'limites',requested:'solicitado',effective:'efetivo',confidence:'confiança descritiva',kind:'tipo',constraint:'restrição',measured:'observado',mode:'modo',approved:'aprovado',opening:'abertura',terminal:'terminal',iAccent:'i acentuado',top:'superior',bottom:'inferior',mark:'marca',contour:'contorno',point:'nó',handle:'alça',left:'margem esquerda',right:'margem direita',advance:'avanço',policy:'tratamento',file:'arquivo',project:'projeto',dimension:'dimensão',references:'referências',glyphs:'glifos',commands:'comandos',styles:'estilos',undo:'desfazer',historyBytes:'bytes do histórico',nodeReduction:'redução de nós',requestedTolerance:'tolerância solicitada',effectiveDeviation:'desvio efetivo',before:'antes',after:'depois'};
 const enums={...RELATION_LABELS,measured:'medido',inferred:'inferido','user-defined':'definido pelo usuário',exact:'preservar exatamente',proportional:'adaptar proporcionalmente',shared:'compartilhado',optical:'correção óptica',faithful:'reconstrução fiel',coherent:'ampliação coerente',regularized:'desenvolvimento regularizado',single:'um andar',double:'dois andares',open:'aberto',closed:'fechado',plain:'sem serifa',serif:'serifa',keep:'preservar',replace:'substituir'};
 if(Array.isArray(value))return value.map(v=>diagnosticPortuguese(v,key));
 if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[labels[k]||FEATURE_LABELS[k]||COMPONENT_LABELS[k]||k,diagnosticPortuguese(v,k)]));
 if(typeof value==='string'&&['relationship','kind','policy','mode','a','g','opening','terminal','iAccent'].includes(key))return enums[value]||value;
 if(typeof value==='string'&&key==='components')return COMPONENT_LABELS[value]||value;
 return value;
}
